--- # this playbook installs httpd, starts httpd service, download the website from repo and install it in the remote server
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: start and enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
  - name: retrieve website from repo
    get_url:
      url: http://repo.example.com/website.tgz
      dest: /tmp/website.tgz
  - name: install website
    unarchive:
      remote_src: yes
      src: /tmp/website.tgz
      dest: /var/www/html
