--- # this yml file displays the usage of variables
- hosts: all
  become: yes
  become_method: sudo
  vars:
    inv_file: /home/ansible/myservers.txt
  tasks:
  - name: create a file
    file:
      path: "{{ inv_file }}"
      state: touch
  - name: Edit my inventory file
    lineinfile:
      path: "{{ inv_file }}"
      line: "{{ groups['labservers'] }}"
